### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.RemoveInactiveObjectsAndDisabledComponents

### ISSUE THREAD

**Issue by omills122** [esperecyan/VRMConverterForVRChat#27] opened 2021-12-11 00:59 UTC
Unity Editor: 2019.4.31f1
VRChat SDK: 2021.11.24.16.20
VRM Converter for VRChat: 30.0.0
UniVRM: 0.90.1

System.NullReferenceException: Object reference not set to an instance of an object
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.RemoveInactiveObjectsAndDisabledComponents (UnityEngine.GameObject instance) [0x00076] in D:\New Unity Project\Library\PackageCache\jp.pokemori.vrm-converter-for-vrchat@30.0.0\Editor\VRChatToVRM\VRChatToVRMConverter.cs:243 
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.Convert (System.String outputPath, UnityEngine.GameObject instance, VRM.VRMMetaObject meta, System.Collections.Generic.IDictionary`2[TKey,TValue] presetVRChatBindingPairs, Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.DynamicBoneReplacer+ParametersConverter swayingParametersConverter) [0x001e6] in D:\New Unity Project\Library\PackageCache\jp.pokemori.vrm-converter-for-vrchat@30.0.0\Editor\VRChatToVRM\VRChatToVRMConverter.cs:172 
  at Esperecyan.Unity.VRMConverterForVRChat.UI.VRChatToVRMWizard.OnWizardCreate () [0x001c4] in D:\New Unity Project\Library\PackageCache\jp.pokemori.vrm-converter-for-vrchat@30.0.0\Editor\UI\VRChatToVRMWizard.cs:262 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.RemoveInactiveObjectsAndDisabledComponents (UnityEngine.GameObject instance) [0x00076] in D:\New Unity Project\Library\PackageCache\jp.pokemori.vrm-converter-for-vrchat@30.0.0\Editor\VRChatToVRM\VRChatToVRMConverter.cs:243 
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.Convert (System.String outputPath, UnityEngine.GameObject instance, VRM.VRMMetaObject meta, System.Collections.Generic.IDictionary`2[TKey,TValue] presetVRChatBindingPairs, Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.DynamicBoneReplacer+ParametersConverter swayingParametersConverter) [0x001e6] in D:\New Unity Project\Library\PackageCache\jp.pokemori.vrm-converter-for-vrchat@30.0.0\Editor\VRChatToVRM\VRChatToVRMConverter.cs:172 
  at Esperecyan.Unity.VRMConverterForVRChat.UI.VRChatToVRMWizard.OnWizardCreate () [0x001c4] in D:\New Unity Project\Library\PackageCache\jp.pokemori.vrm-converter-for-vrchat@30.0.0\Editor\UI\VRChatToVRMWizard.cs:262 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 

Get this error when export vrm file from vrchat avatar

**Comment by esperecyan** [comment] 2021-12-11 01:08
Thank you for your report.
Can you provide model and steps to reproduce the problem?

**Comment by omills122** [comment] 2021-12-12 03:40
Model is: https://booth.pm/en/items/3379542

I am taking prefab, unpacking completely, then deleting unused items/costumes/setting costumes and hitting export vrm from vrchat avatar.

**Comment by esperecyan** [comment] 2021-12-16 05:43
Since I do not have a 3D model that can reproduce the problem, I am unable to investigate the cause.

**Comment by esperecyan** [comment] 2023-11-09 05:44
Does this issue also occur with VRM Converter for VRChat v40.1.1?

**Comment by esperecyan** [comment] 2024-02-23 08:45
There is no reply, so I close this.

**Closed by esperecyan** 2024-02-23 08:45 UTC
Labels: bug, help wanted, question, VRChat→VRM
