### ISSUE TITLE
VRM Export errors from bad Thumbnail texture read: "textureImporter.textureType Cursor is not supported. Only Default or NormalMap is supported"

### ISSUE THREAD

**Issue by RiskiVR** [esperecyan/VRMConverterForVRChat#61] opened 2023-10-31 18:40 UTC
# VRM Export errors from bad Thumbnail texture read

When attempting to Export VRM File, I get this error: `System.ArgumentException: In (UnityEngine.Texture2D): textureImporter.textureType Cursor is not supported. Only Default or NormalMap is supported`

It appears to be referencing the Thumbnail texture, which is not set to Cursor. It is a Default image type.
This is confirmed to be the Thumbnail texture as removing the Thumbnail image resulted in this error: `System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index`

## Here is what the Settings window looks like:
![image](https://github.com/esperecyan/VRMConverterForVRChat/assets/40964931/69785cf7-2ae8-4ae3-8255-28077f16a707)

### With Thumbnail
```
Unity Editor: 2019.4.31f1
VRM Converter for VRChat: 40.1.1
UniVRM: 0.110.0

System.ArgumentException: In (UnityEngine.Texture2D): textureImporter.textureType Cursor is not supported. Only Default or NormalMap is supported
  at VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile (UnityEngine.Texture texture, VRMShaders.ColorSpace exportColorSpace) [0x0005a] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Editor\Texture\Exporter\EditorTextureSerializer.cs:45 
  at VRMShaders.TextureExporter.ConvertTextureSimple (UnityEngine.Texture src, System.Boolean needsAlpha, VRMShaders.ColorSpace exportColorSpace) [0x0000a] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Runtime\Texture\Exporter\TextureExporter.cs:171 
  at VRMShaders.TextureExporter+<>c__DisplayClass9_0.<RegisterExportingSimple>b__0 () [0x00000] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Runtime\Texture\Exporter\TextureExporter.cs:82 
  at (wrapper delegate-invoke) System.Func`1[System.ValueTuple`2[UnityEngine.Texture2D,System.Boolean]].invoke_TResult()
  at VRMShaders.TextureExporter.Export () [0x00019] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Runtime\Texture\Exporter\TextureExporter.cs:51 
  at UniGLTF.gltfExporter.Export (VRMShaders.ITextureSerializer textureSerializer) [0x0053d] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.gltf\Runtime\UniGLTF\IO\gltfExporter.cs:333 
  at VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, System.Collections.Generic.List`1[T] destroy) [0x0029c] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.univrm\Editor\Format\VRMEditorExporter.cs:237 
  at VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings) [0x00008] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.univrm\Editor\Format\VRMEditorExporter.cs:25 
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.Convert (System.String version, System.String outputPath, UnityEngine.GameObject instance, VRM.VRMMetaObject meta, System.Collections.Generic.IDictionary`2[TKey,TValue] presetVRChatBindingPairs, System.Boolean keepUnusedShapeKeys) [0x00245] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\VRChatToVRM\VRChatToVRMConverter.cs:188 
  at Esperecyan.Unity.VRMConverterForVRChat.UI.VRChatToVRMWizard.OnWizardCreate () [0x001c4] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\UI\VRChatToVRMWizard.cs:315 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile (UnityEngine.Texture texture, VRMShaders.ColorSpace exportColorSpace) [0x0005a] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Editor\Texture\Exporter\EditorTextureSerializer.cs:45 
  at VRMShaders.TextureExporter.ConvertTextureSimple (UnityEngine.Texture src, System.Boolean needsAlpha, VRMShaders.ColorSpace exportColorSpace) [0x0000a] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Runtime\Texture\Exporter\TextureExporter.cs:171 
  at VRMShaders.TextureExporter+<>c__DisplayClass9_0.<RegisterExportingSimple>b__0 () [0x00000] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Runtime\Texture\Exporter\TextureExporter.cs:82 
  at (wrapper delegate-invoke) System.Func`1[System.ValueTuple`2[UnityEngine.Texture2D,System.Boolean]].invoke_TResult()
  at VRMShaders.TextureExporter.Export () [0x00019] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.vrmshaders\GLTF\IO\Runtime\Texture\Exporter\TextureExporter.cs:51 
  at UniGLTF.gltfExporter.Export (VRMShaders.ITextureSerializer textureSerializer) [0x0053d] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.gltf\Runtime\UniGLTF\IO\gltfExporter.cs:333 
  at VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, System.Collections.Generic.List`1[T] destroy) [0x0029c] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.univrm\Editor\Format\VRMEditorExporter.cs:237 
  at VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings) [0x00008] in C:\Users\foxyt\Documents\Mattias Merino\Packages\com.vrmc.univrm\Editor\Format\VRMEditorExporter.cs:25 
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.Convert (System.String version, System.String outputPath, UnityEngine.GameObject instance, VRM.VRMMetaObject meta, System.Collections.Generic.IDictionary`2[TKey,TValue] presetVRChatBindingPairs, System.Boolean keepUnusedShapeKeys) [0x00245] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\VRChatToVRM\VRChatToVRMConverter.cs:188 
  at Esperecyan.Unity.VRMConverterForVRChat.UI.VRChatToVRMWizard.OnWizardCreate () [0x001c4] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\UI\VRChatToVRMWizard.cs:315 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 
```

### Without Thumbnail
```
Unity Editor: 2019.4.31f1
VRM Converter for VRChat: 40.1.1
UniVRM: 0.110.0

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () [0x00017] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at Esperecyan.UniVRMExtensions.VRMInitializer.Initialize (System.String prefabPath, UnityEngine.GameObject prefabInstance) [0x000ac] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.univrm-extensions\VRMInitializer.cs:40 
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.Convert (System.String version, System.String outputPath, UnityEngine.GameObject instance, VRM.VRMMetaObject meta, System.Collections.Generic.IDictionary`2[TKey,TValue] presetVRChatBindingPairs, System.Boolean keepUnusedShapeKeys) [0x00245] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\VRChatToVRM\VRChatToVRMConverter.cs:188 
  at Esperecyan.Unity.VRMConverterForVRChat.UI.VRChatToVRMWizard.OnWizardCreate () [0x001c4] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\UI\VRChatToVRMWizard.cs:315 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () [0x00017] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at Esperecyan.UniVRMExtensions.VRMInitializer.Initialize (System.String prefabPath, UnityEngine.GameObject prefabInstance) [0x000ac] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.univrm-extensions\VRMInitializer.cs:40 
  at Esperecyan.Unity.VRMConverterForVRChat.VRChatToVRM.VRChatToVRMConverter.Convert (System.String version, System.String outputPath, UnityEngine.GameObject instance, VRM.VRMMetaObject meta, System.Collections.Generic.IDictionary`2[TKey,TValue] presetVRChatBindingPairs, System.Boolean keepUnusedShapeKeys) [0x00245] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\VRChatToVRM\VRChatToVRMConverter.cs:188 
  at Esperecyan.Unity.VRMConverterForVRChat.UI.VRChatToVRMWizard.OnWizardCreate () [0x001c4] in C:\Users\foxyt\Documents\Mattias Merino\Packages\jp.pokemori.vrm-converter-for-vrchat\Editor\UI\VRChatToVRMWizard.cs:315 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 
```

**Comment by esperecyan** [comment] 2023-11-09 05:50
Does this error also occur when exporting with “Export to VRM 0.x”?

If it does not occur with the above, does it also occur when you do “プレハブバリアントを作ってVRMプレハブ化”?

**Comment by RiskiVR** [comment] 2023-11-11 00:05
Hello, sorry for not responding sooner.

Yes, the same error occurred when using "Export to VRM 0.x"

As for the “プレハブバリアントを作ってVRMプレハブ化” option, I got this: 
![image](https://github.com/esperecyan/VRMConverterForVRChat/assets/40964931/5b1f18c2-1ee0-4bc0-ba81-2add5288e95b)

**Comment by esperecyan** [comment] 2023-11-11 00:24
Thank you for the verification.  
Since the error occurs with UniVRM alone, it does not seem to be an issue with the VRM Converter for VRChat.

Please create a project with Unity 2021.3 or Unity 2022.3 and install UniVRM-0.115.0.
If the error does not occur with “Export to VRM 0.x” in UniVRM-0.115.0, then the problem is caused by the Unity version that the VRChat SDK supports being too old.  
https://feedback.vrchat.com/feature-requests/p/update-to-unity-20213-lts  
https://ask.vrchat.com/t/developer-update-9-november-2023/20710#sdk-for-unity-2022-progress-12

If the error still occurs with “Export to VRM 0.x” in UniVRM-0.115.0, then it is a problem in UniVRM and report to UniVRM issues.  
https://github.com/vrm-c/UniVRM/issues

**Comment by RiskiVR** [comment] 2023-11-11 21:53
Problem is that VRChat still uses Unity 2019.4.31f1 for avatar creation. The version of UniVRM used to work just fine for my avatar, and for whatever reason this is happening on a different project despite being the same Unity version.

However I discovered that the version I used that's causing issues is UniVRM-0.110.0, and the previous version I used that did work was UniVRM-0.99.0. Either way it doesn't seem to be working anymore.

I guess I'll have to create a separate project for VRM converts now.. Which sucks cuz it was nice being able to do it within the same project as the VRC avatar.

**Comment by esperecyan** [comment] 2023-11-11 23:26
Yes, it is VRChat that is complicating matters.

If you can see that you can export successfully with “Export to VRM 0.x” in UniVRM-0.99.0, then this may be a regression in UniVRM. If you can see that you can export successfully with “Export to VRM 0.x”  in UniVRM-0.115.0, then the regression may have been fixed.

In any case, without a procedure to reproduce this issue in my environment, I am also unable to report it to UniVRM issues on your behalf.

**Comment by RiskiVR** [comment] 2024-02-23 10:14
I have not tested this yet, I will give the latest build a try and get back to you!

**Comment by esperecyan** [comment] 2024-06-15 10:38
There is no reply, so I close this.

**Closed by esperecyan** 2024-06-15 10:38 UTC
Labels: question, VRChat→VRM
